### ISSUE TITLE
Update needed in your termux repo

### ISSUE THREAD

**Issue by MikeAndarsons** [rendiix/termux-apktool#3]
i used "curl -s https://raw.githubusercontent.com/rendiix/termux-apktool/main/install.sh | bash " this command and it installed 2.7.1 apktool snapshot,So update to latest in your termux repo

**Comment by ahmad24shargh** [comment]
download aarch64(or arm) snapshot .deb package and install it directly :



<CODE>
apt install ./apktool_2.8.2-TERMUX-SNAPSHOT-1243dd5_aarch64.deb
</CODE>
